# -*- coding: utf-8 -*-
"""Projeto_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z_LmdeT1MiWyhqdBmk2EERtGYtHpFrF2

# Projeto Final Unidade I
Nome: Incêndios Florestais no Brasil

Professor: IVANOVITCH MEDEIROS DANTAS DA SILVA


1.   Problemática

Relátorio sobre índice de incêndios Florestais ocorridos no Brasil.
2.   Fonte dos Dados:

  [Kaggle](https://www.kaggle.com/gustavomodelli/forest-fires-in-brazil)

  [DN](https://www.dn.pt/lusa/incendios-um-dos-maiores-fogos-queimou-41-
  mil-hectares-em-2003-8577610.html)

  [UOL](https://escolakids.uol.com.br/ciencias/estacoes-do-ano.htm)

#*BIBLIOTECAS*
"""

# Bibliotecas que serão utilizadas:

# Biblioteca para gerir sequencias de dados
import numpy as np

# Biblioteca para criar/editar planilhas de dados
import pandas as pd

# Biblioteca para plotagem de gráficos
import matplotlib.pyplot as plt

# Recebendo e lendo o arquivo "CSV" direto do repositorio do "Github"
dados = pd.read_csv(
'https://raw.githubusercontent.com/Julio-CSilva/Projeto_Finally_U1_TopicosD/main/data/amazon.csv',
    sep=',',
    header=[0],
)

# sep (definindo que a separação das colunas é demarcada por ',')
# header (define que o cabeçalho é definido como sendo a linha '0')


# Mudando os títulos das colunas:
dados.columns = ['Ano', 'Estado', 'Mês', 'N_Queimadas', 'Data']

# Mudando o nome Rio -> Rio de Janeiro
dados = dados.replace({'Estado': {'Rio': np.nan}})
dados['Estado'].fillna('Rio de Janeiro', inplace=True)

# Configuração GERAL de tamanho para todos os gráficos
plt.rcParams['figure.figsize'] = (18, 8)

# Lendo as 1000 primeiras linhas do arquivo
dados.head(1000)

# Entre os anos de 1998 á 2017, tivemos a seguinte média de relatos de
# incêndios por MÊS

queimadas_totais_mes = (dados['N_Queimadas'].sum()) / 12
print(
    "A Média de Relatos de Incêndios Florestais entre os anos de 1998 e 2017 a cada mês é de: ",
    queimadas_totais_mes,
    " Casos")

queimadas_estado = dados.groupby('Estado')['N_Queimadas'].mean()

queimadas_estado.plot(linestyle='--', color='black', marker='s')
queimadas_estado.plot.bar(edgecolor='black', grid=True, linewidth=1.5)

plt.ylim(0, 250)
plt.ylabel('Casos de Incêndio')
plt.title('Números de Casos por Estado', fontsize=18)
plt.legend(loc='best')

plt.show()

queimadas_ano = dados.groupby('Ano')['N_Queimadas'].mean()

m_e = [
    6,
    8,
    8,
    8,
    12,
    13,
    12,
    11,
    10,
    10,
    9,
    12,
    11,
    10,
    12,
    10,
    12,
    12,
    13,
    12]

queimadas_ano.plot.barh(
    edgecolor='black',
    color='c',
    width=0.7,
    xerr=m_e,
    capsize=5,
    ecolor='gray')

plt.xlim(0, 160)
plt.title('Números de Casos por Ano', fontsize=18)
plt.xlabel('Casos de Incêndio')
plt.legend()


plt.show()

queimadas_mes = dados.groupby('Mês')['N_Queimadas'].mean()

explode = (0, 0.2, 0, 0, 0, 0.2, 0.1, 0, 0, 0, 0.1, 0.1)
cores = [
    'steelblue',
    'Gold',
    'darkorchid',
    'm',
    'orange',
    'G',
    'Dodgerblue',
    'lightgreen',
    'cyan',
    'purple',
    'Salmon',
    'r']

queimadas_mes.plot.pie(
    explode=explode,
    shadow=True,
    autopct='%1.1f%%',
    startangle=180,
    colors=cores)

plt.title('Número de Casos por Mês', fontsize=18)
plt.legend(fontsize=15)
plt.axis('equal')

plt.show()
